"""STANDALONE Hunter bot — generated by bots/bundle.py. DO NOT EDIT BY HAND.

Single self-contained file: imports only `requests` + stdlib, so the game
server can run it via `python -u "<this file>" <server_url> <game_id> <name>`
from anywhere, even when copied away from the repo.

Regenerate after changing any source module:  python -m bots.tools.bundle
"""
from __future__ import annotations
import sys


# ===== inlined from cli/models.py =====
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional
import networkx as nx


class FieldType(IntEnum):
    BASE = 0
    NORMAL = 1
    OBSTACLE_SLOW = 2
    OBSTACLE = 3
    POWERUP = 4
    WALL = 5
    EMPTY = 6
    
    def movement_cost(self) -> int:
        match self:
            case FieldType.BASE | FieldType.NORMAL | FieldType.OBSTACLE | FieldType.POWERUP:
                return 1
            case FieldType.OBSTACLE_SLOW:
                return 2
            case _:
                return 1000

    def spike_damage(self) -> int:
        return 10 if self == FieldType.OBSTACLE else 0


class Status(IntEnum):
    Normal = 0
    Fatigue = 1
    Frozen = 2
    Dizzy = 3


class ItemType(IntEnum):
    NONE = 0
    Healing = 1
    Movement = 2
    Defense = 3
    Utility = 4
    CrowdControl = 5
    Attack = 6


@dataclass
class Position:
    x: int
    y: int


@dataclass
class Item:
    id: int
    name: str
    uses: Optional[int]
    effect: Optional[str]
    range: Optional[int]
    power: Optional[int]
    duration: Optional[int]
    item_type: ItemType


@dataclass
class Entity:
    id: int
    name: str
    health: int
    max_health: int
    attack_power: int
    attack_range: int
    max_move_distance: int
    position: Position
    summoned_by: Optional[int]
    active_statuses: dict[Status, int]
    x_pattern: list[int]
    y_pattern: list[int]


@dataclass
class MonsterCard:
    id: int
    name: str
    uses: Optional[int]
    effect: Optional[str]
    power: int
    on_cooldown: bool
    cooldown: int
    cooldown_counter: int
    monster: Optional[Entity]


@dataclass
class Player:
    id: int
    name: str
    health: int
    max_health: int
    attack_power: int
    attack_range: int
    max_move_distance: int
    position: Position
    summoned_by: Optional[int]
    active_statuses: dict[Status, int]
    x_pattern: list[int]
    y_pattern: list[int]
    level: int
    xp: int
    inventory: list[Item]
    cards: list[MonsterCard]
    first: bool


@dataclass
class Obstacle:
    type: str
    damage: int
    cooldown: int
    current_cooldown: int


@dataclass
class FieldInfo:
    position: Optional[Position]
    entity: Optional[Entity]
    field_type: FieldType
    owner: Optional[Player]
    item: Optional[Item]
    monster_card: Optional[MonsterCard]
    obstacle: Optional[Obstacle]
    
    def is_occupied(self):
        return self.entity or self.item or self.monster_card


@dataclass
class Map:
    x: int
    y: int
    name: str
    grid: list[FieldInfo]
    maxMoveDistance: int
    graph: nx.DiGraph = field(init=False)

    def __post_init__(self):
        self.graph = nx.DiGraph()
        self.graph.add_nodes_from(range(len(self.grid)))
        for cell in self.grid:
            self._findAllPossible(cell)
            
    def pair_to_index(self, x: int, y: int) -> int:
        return x * self.y + y
    
    def index_to_pair(self, index: int) -> tuple[int, int]:
        return (index // self.y, index % self.y)

    def get_cell(self, x: int, y: int) -> Optional[FieldInfo]:
        if self._checkCoords(Position(x, y)):
            return self.grid[self.pair_to_index(x, y)]
        return None
        
    def _checkCoords(self, pos: Position):
        return pos.x >= 0 and pos.x < self.x and pos.y >= 0 and pos.y < self.y
    
    def _movement_cost(self, pos: Position) -> int:
        field = self.get_cell(pos.x, pos.y)
        return field.field_type.movement_cost() if self._checkCoords(pos) and not field.is_occupied() else 1000
    
    def _findAllPossible(self, field: FieldInfo):
        field_pos = field.position
        if field_pos is None:
            return
        dirs = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        for d in dirs:
            total_spike_damage = self.get_cell(field_pos.x, field_pos.y).field_type.spike_damage()
            movementRemaining = self.maxMoveDistance
            if field.field_type == FieldType.OBSTACLE_SLOW:
                movementRemaining -= 1
            cur_pos = Position(field_pos.x + d[0], field_pos.y + d[1])
            movementRemaining -= self._movement_cost(cur_pos)
            while movementRemaining >= 0:
                total_spike_damage += self.get_cell(cur_pos.x, cur_pos.y).field_type.spike_damage()
                self.graph.add_edge(
                    self.pair_to_index(field_pos.x, field_pos.y),
                    self.pair_to_index(cur_pos.x, cur_pos.y),
                    weight = total_spike_damage
                )
                cur_pos = Position(cur_pos.x + d[0], cur_pos.y + d[1])
                movementRemaining -= self._movement_cost(cur_pos)
            

@dataclass
class GameState:
    game_id: str
    state_str: str
    current_turn: int
    players: dict[str, Player]
    map: Map


def _g(d: dict, key: str, default=None):
    v = d.get(key)
    if v is not None:
        return v
    camel = key[0].lower() + key[1:]
    v = d.get(camel)
    if v is not None:
        return v
    return default


def _parse_position(d: Optional[dict]) -> Optional[Position]:
    if not d:
        return None
    return Position(x=_g(d, "X", 0), y=_g(d, "Y", 0))


def _parse_statuses(d: Optional[dict]) -> dict[Status, int]:
    if not d:
        return {}
    out: dict[Status, int] = {}
    for k, v in d.items():
        try:
            out[Status(int(k))] = v
        except (ValueError, KeyError):
            for s in Status:
                if s.name.lower() == str(k).lower():
                    out[s] = v
                    break
    return out


def _parse_item(d: Optional[dict]) -> Optional[Item]:
    if not d:
        return None
    return Item(
        id=_g(d, "Id", 0),
        name=_g(d, "Name", ""),
        uses=_g(d, "Uses"),
        effect=_g(d, "Effect"),
        range=_g(d, "Range"),
        power=_g(d, "Power"),
        duration=_g(d, "Duration"),
        item_type=ItemType(_g(d, "ItemType", 0)),
    )


def _parse_entity(d: Optional[dict]) -> Optional[Entity]:
    if not d:
        return None
    return Entity(
        id=_g(d, "Id", 0),
        name=_g(d, "Name", ""),
        health=_g(d, "Health", 0),
        max_health=_g(d, "MaxHealth", 0),
        attack_power=_g(d, "AttackPower", 0),
        attack_range=_g(d, "AttackRange", 0),
        max_move_distance=_g(d, "MaxMoveDistance", 0),
        position=_parse_position(_g(d, "Position")) or Position(0, 0),
        summoned_by=_g(d, "SummonedByPlayerId"),
        active_statuses=_parse_statuses(_g(d, "ActiveStatuses")),
        x_pattern=d.get("xPattern") or [],
        y_pattern=d.get("yPattern") or [],
    )


def _parse_monster_card(d: Optional[dict]) -> Optional[MonsterCard]:
    if not d:
        return None
    return MonsterCard(
        id=_g(d, "Id", 0),
        name=_g(d, "Name", ""),
        uses=_g(d, "Uses"),
        effect=_g(d, "Effect"),
        power=_g(d, "Power", 0),
        on_cooldown=_g(d, "OnCooldown", False),
        cooldown=_g(d, "Cooldown", 0),
        cooldown_counter=_g(d, "CooldownCounter", 0),
        monster=_parse_entity(_g(d, "Monster")),
    )


def _parse_player(d: Optional[dict]) -> Optional[Player]:
    if not d:
        return None
    return Player(
        id=_g(d, "Id", 0),
        name=_g(d, "Name", ""),
        health=_g(d, "Health", 0),
        max_health=_g(d, "MaxHealth", 100),
        attack_power=_g(d, "AttackPower", 0),
        attack_range=_g(d, "AttackRange", 0),
        max_move_distance=_g(d, "MaxMoveDistance", 0),
        position=_parse_position(_g(d, "Position")) or Position(0, 0),
        summoned_by=_g(d, "SummonedByPlayerId"),
        active_statuses=_parse_statuses(_g(d, "ActiveStatuses")),
        x_pattern=d.get("xPattern") or [],
        y_pattern=d.get("yPattern") or [],
        level=_g(d, "Level", 0),
        xp=_g(d, "Xp", 0),
        inventory=[_parse_item(i) for i in (_g(d, "Inventory") or []) if i],
        cards=[_parse_monster_card(c) for c in (_g(d, "Cards") or []) if c],
        first=bool(_g(d, "First", False)),
    )


def _parse_obstacle(d: Optional[dict]) -> Optional[Obstacle]:
    if not d:
        return None
    return Obstacle(
        type=_g(d, "Type", ""),
        damage=_g(d, "Damage", 0),
        cooldown=_g(d, "Cooldown", 0),
        current_cooldown=_g(d, "CurrentCooldown", 0),
    )


def _parse_field_info(d: dict) -> FieldInfo:
    return FieldInfo(
        position=_parse_position(_g(d, "Position")),
        entity=_parse_entity(_g(d, "Entity")),
        field_type=FieldType(_g(d, "FieldType", 1)),
        owner=_parse_player(_g(d, "Owner")),
        item=_parse_item(_g(d, "Item")),
        monster_card=_parse_monster_card(_g(d, "MonsterCard")),
        obstacle=_parse_obstacle(_g(d, "Obstacle")),
    )


def _parse_map(d: Optional[dict], maxMoveDistance: int) -> Optional[Map]:
    if not d:
        return None
    return Map(
        x=_g(d, "X", 32),
        y=_g(d, "Y", 16),
        name=_g(d, "Name", ""),
        grid=[_parse_field_info(f) for f in (_g(d, "Grid") or [])],
        maxMoveDistance = maxMoveDistance,
    )


def parse_game_state(d: dict) -> GameState:
    players_raw = _g(d, "Players") or {}
    players = {k: p for k, v in players_raw.items() if (p := _parse_player(v))}
    max_move_distance = next(
        (p.max_move_distance for p in players.values()), 
        4
    )
    return GameState(
        game_id=_g(d, "GameId") or _g(d, "Id") or "",
        state_str=_g(d, "GameState", ""),
        current_turn=_g(d, "TurnCounter", 0),
        players=players,
        map=_parse_map(_g(d, "Map"), max_move_distance) or Map(32, 16, "", []),
    )


def parse_action_response(d: dict) -> tuple[Optional[Map], Optional[Player]]:
    player = _parse_player(_g(d, "Player"))
    max_move_distance = player.max_move_distance if player is not None else 4
    
    return (_parse_map(_g(d, "Map"), max_move_distance), player)


# ===== inlined from bots/engine/types.py =====
from dataclasses import dataclass
from typing import Optional, Callable



@dataclass
class Action:
    kind: str
    target_x: Optional[int] = None
    target_y: Optional[int] = None
    target_id: Optional[int] = None
    item_id: Optional[int] = None
    card_id: Optional[int] = None
    rule_name: str = ""


@dataclass
class RuleContext:
    state: GameState
    me: Player
    enemy: Optional[Player]
    turn: int


Rule = Callable[[RuleContext], Optional[Action]]


# ===== inlined from bots/engine/helpers/geometry.py =====
from typing import Optional



MAP_X = 32
MAP_Y = 16
CARDINALS = [(1, 0), (-1, 0), (0, 1), (0, -1)]


def in_bounds(x: int, y: int) -> bool:
    return 0 <= x < MAP_X and 0 <= y < MAP_Y


def tile_at(m: Map, x: int, y: int) -> Optional[FieldInfo]:
    if not in_bounds(x, y):
        return None
    return m.get_cell(x, y)


def manhattan(a: Position, b: Position) -> int:
    return abs(a.x - b.x) + abs(a.y - b.y)


def is_adjacent(a: Position, b: Position) -> bool:
    return manhattan(a, b) == 1


def orthogonal_neighbors(pos: Position) -> list[tuple[int, int]]:
    return [(pos.x + dx, pos.y + dy) for dx, dy in CARDINALS if in_bounds(pos.x + dx, pos.y + dy)]


def nearest_xy(from_pos: Position, candidates: list[tuple[int, int]]) -> Optional[tuple[int, int]]:
    if not candidates:
        return None
    return min(candidates, key=lambda xy: abs(xy[0] - from_pos.x) + abs(xy[1] - from_pos.y))


# ===== inlined from bots/engine/helpers/inventory.py =====
from typing import Optional



ICE_CUBE_CARD_NAME = "Card of Ice Cubes"
ITEM_HEAL_NAME = "Kristal života"
ITEM_FREEZE_NAME = "Freeze scroll"
ITEM_DIZZY_NAME = "Dizzy scroll"


def _is_ice_cube_card(c: MonsterCard) -> bool:
    return (c.name or "").strip().lower() == ICE_CUBE_CARD_NAME.lower()


def _is_mage_card(c: MonsterCard) -> bool:
    return not _is_ice_cube_card(c) and (c.power or 0) >= 35


def _is_warrior_card(c: MonsterCard) -> bool:
    return not _is_ice_cube_card(c) and (c.power or 0) < 35


def available_cube_cards(me: Player) -> list[MonsterCard]:
    return [c for c in me.cards
            if _is_ice_cube_card(c) and c.cooldown_counter == 0 and (c.uses or 0) > 0]


def available_warrior_cards(me: Player) -> list[MonsterCard]:
    return [c for c in me.cards
            if _is_warrior_card(c) and c.cooldown_counter == 0 and (c.uses or 0) > 0]


def available_mage_cards(me: Player) -> list[MonsterCard]:
    return [c for c in me.cards
            if _is_mage_card(c) and c.cooldown_counter == 0 and (c.uses or 0) > 0]


def count_cards(me: Player) -> int:
    return len(me.cards or [])


def pick_card_max_uses(cards: list[MonsterCard]) -> Optional[MonsterCard]:
    if not cards:
        return None
    return max(cards, key=lambda c: c.uses or 0)


def find_item_by_name(me: Player, name: str) -> Optional[Item]:
    target = name.strip().lower()
    for it in me.inventory:
        if (it.name or "").strip().lower() == target:
            return it
    return None


def has_status(p: Player, s: Status) -> bool:
    return p.active_statuses.get(s, 0) > 0


def is_fatigued(p: Player) -> bool:
    return has_status(p, Status.Fatigue)


def has_heal(me: Player) -> bool:
    return find_item_by_name(me, ITEM_HEAL_NAME) is not None


def has_freeze(me: Player) -> bool:
    return find_item_by_name(me, ITEM_FREEZE_NAME) is not None


def count_item_by_name(me: Player, name: str) -> int:
    target = name.strip().lower()
    return sum(1 for it in me.inventory if (it.name or "").strip().lower() == target)


def count_freeze(me: Player) -> int:
    return count_item_by_name(me, ITEM_FREEZE_NAME)

def count_heal(me: Player) -> int:
    return count_item_by_name(me, ITEM_HEAL_NAME)


# ===== inlined from bots/engine/helpers/shrink.py =====
SHRINK_SETUP_TURNS = {13, 14, 28, 29, 43, 44}


def shrink_danger_columns_for_turn(turn: int) -> set[int]:
    if turn < 15:
        return set(list(range(0, 3)) + list(range(29, 32)))
    if turn < 30:
        return set(list(range(3, 6)) + list(range(26, 29)))
    return set()


def is_in_bridge_wall_zone(pos: Position) -> bool:
    in_band = (6 <= pos.x <= 12) or (20 <= pos.x <= 27)
    return in_band and (pos.y <= 3 or pos.y >= 12)


def in_shrink_danger(pos: Position, turn: int) -> bool:
    eps = 5
    if turn < 15 and turn >= 15 - eps:
        return pos.x in {0, 1, 2, 29, 30, 31}
    if turn < 30 and turn >= 30 - eps:
        return pos.x in {3, 4, 5, 26, 27, 28}
    if turn < 45 and turn >= 45 - eps:
        return is_in_bridge_wall_zone(pos)
    return False


def filter_safe(reachable: set[tuple[int, int]], turn: int) -> set[tuple[int, int]]:
    if turn >= 45:
        return reachable
    if turn >= 30:
        return {(x, y) for (x, y) in reachable if not is_in_bridge_wall_zone(Position(x, y))}
    danger = shrink_danger_columns_for_turn(turn)
    return {(x, y) for (x, y) in reachable if x not in danger}


# ===== inlined from bots/engine/helpers/scan.py =====
from typing import Iterable, Optional




def iter_cells(m: Map) -> Iterable[tuple[int, int, FieldInfo]]:
    for x in range(MAP_X):
        for y in range(MAP_Y):
            t = m.get_cell(x, y)
            if t is not None:
                yield x, y, t


def find_card_tiles(state: GameState, card_id: Optional[int] = None) -> list[tuple[int, int]]:
    if card_id is not None:
        return [(x, y) for x, y, t in iter_cells(state.map)
                if t.monster_card is not None and t.monster_card.id == card_id]
    return [(x, y) for x, y, t in iter_cells(state.map)
            if t.monster_card is not None and _is_ice_cube_card(t.monster_card)]


def find_item_tiles(state: GameState, item_id: Optional[int] = None,
                    item_name: Optional[str] = None) -> list[tuple[int, int]]:
    if item_name is not None:
        target = item_name.strip().lower()
        return [(x, y) for x, y, t in iter_cells(state.map)
                if t.item is not None and (t.item.name or "").strip().lower() == target]
    if item_id is not None:
        return [(x, y) for x, y, t in iter_cells(state.map)
                if t.item is not None and t.item.id == item_id]
    return []


def find_allied_summons(state: GameState, me: Player) -> list:
    out = []
    for _, _, t in iter_cells(state.map):
        if t.entity and t.entity.summoned_by == me.id:
            out.append(t.entity)
    return out


def adjacent_card_tile(state: GameState, me: Player,
                       ice_cube_only: bool = False) -> Optional[tuple[int, int]]:
    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(state.map, nx, ny)
        if not t or t.monster_card is None:
            continue
        if ice_cube_only and not _is_ice_cube_card(t.monster_card):
            continue
        return (nx, ny)
    return None


def adjacent_item_tile(state: GameState, me: Player, item_id: Optional[int] = None,
                       item_name: Optional[str] = None) -> Optional[tuple[int, int]]:
    target_name = item_name.strip().lower() if item_name else None
    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(state.map, nx, ny)
        if not t or t.item is None:
            continue
        if target_name is not None:
            if (t.item.name or "").strip().lower() == target_name:
                return (nx, ny)
            continue
        if item_id is not None:
            if t.item.id == item_id:
                return (nx, ny)
            continue
        return (nx, ny)
    return None


# ===== inlined from bots/engine/helpers/movement.py =====
import collections
from typing import Callable, Optional



def bfs_path(state: GameState, start: tuple[int, int],
             is_goal: Callable[[tuple[int, int]], bool],
             turn: Optional[int] = None,
             health: int = 100) -> Optional[list[tuple[int, int]]]:
    if is_goal(start):
        return [start]
    G = state.map.graph
    visited = [[False] * state.map.y for _ in range(state.map.x)]
    queue: collections.deque = collections.deque()
    queue.append((start, [start], 0))
    shortest_path = 1000
    best_path = []
    best_damage = 1000
    while queue:
        (index_x, index_y), path, damage = queue.popleft()
        if visited[index_x][index_y]:
            continue
        if shortest_path != 1000 and len(path) >= shortest_path:
            break
        visited[index_x][index_y] = True
        index = state.map.pair_to_index(index_x, index_y)
        for neighbor, attrs in G[index].items():
            weight = attrs.get("weight", 0)
            nx, ny = state.map.index_to_pair(neighbor)
            new_path = path + [(nx, ny)]
            new_damage = damage + weight
            if (turn is not None and in_shrink_danger(Position(nx, ny), turn)) or new_damage >= health:
                continue
            if is_goal((nx, ny)):
                if shortest_path == 1000:
                    shortest_path = len(new_path)
                if best_damage > new_damage:
                    best_damage = new_damage
                    best_path = new_path
            queue.append(((nx, ny), new_path, new_damage))
    return best_path


def reachable_positions(state: GameState, me: Player) -> set[tuple[int, int]]:
    m = state.map
    idx = m.pair_to_index(me.position.x, me.position.y)
    if idx not in m.graph:
        return set()
    return {m.index_to_pair(n) for n in m.graph.neighbors(idx)}


def bfs_step_toward(state: GameState, me: Player,
                    is_goal: Callable[[tuple[int, int]], bool],
                    turn: int) -> Optional[tuple[int, int]]:
    path = bfs_path(state, (me.position.x, me.position.y), is_goal, turn=turn)
    return None if not path or len(path) < 2 else path[1]


def step_away_from(reachable: set[tuple[int, int]], me: Player,
                   target_xy: tuple[int, int], turn: int) -> Optional[tuple[int, int]]:
    pool = list(filter_safe(reachable, turn))
    if not pool:
        return None
    tx, ty = target_xy
    return max(pool, key=lambda xy: abs(xy[0] - tx) + abs(xy[1] - ty))


def dizzy_request_position(me_pos: Position, desired: tuple[int, int]) -> tuple[int, int]:
    rx = max(0, min(MAP_X - 1, 2 * me_pos.x - desired[0]))
    ry = max(0, min(MAP_Y - 1, 2 * me_pos.y - desired[1]))
    return (rx, ry)


# ===== inlined from bots/engine/helpers/combat.py =====
from typing import Optional




SPIKE_DAMAGE = 10


def can_summon_on(state: GameState, pos: Position, target_xy: tuple[int, int]) -> bool:
    tx, ty = target_xy
    if abs(tx - pos.x) + abs(ty - pos.y) != 1:
        return False
    t = tile_at(state.map, tx, ty)
    if t is None:
        return False
    if t.field_type in (FieldType.WALL, FieldType.EMPTY):
        return False
    return t.entity is None


def summon_targets(state: GameState, me: Player) -> list[tuple[int, int]]:
    return [xy for xy in orthogonal_neighbors(me.position) if can_summon_on(state, me.position, xy)]


def attackable_adjacent_enemy_tile(me: Player, enemy: Player) -> Optional[tuple[int, int]]:
    if not is_adjacent(me.position, enemy.position):
        return None
    return (enemy.position.x, enemy.position.y)


def attackable_adjacent_summon(state: GameState, me: Player, enemy: Optional[Player]) -> Optional[int]:
    if enemy is None:
        return None
    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(state.map, nx, ny)
        if t and t.entity and t.entity.summoned_by == enemy.id:
            return t.entity.id
    return None


# ===== inlined from bots/engine/helpers/threat.py =====
from typing import Iterable, Optional




DEFAULT_X_PATTERN = [1, -1, 0, 0]
DEFAULT_Y_PATTERN = [0, 0, 1, -1]


def _patterns(entity) -> tuple[list[int], list[int]]:
    xp = entity.x_pattern or DEFAULT_X_PATTERN
    yp = entity.y_pattern or DEFAULT_Y_PATTERN
    n = min(len(xp), len(yp))
    return xp[:n], yp[:n]


def _is_fatigued(entity) -> bool:
    return entity.active_statuses.get(Status.Fatigue, 0) > 0


def entity_threat_tiles(entity, *, in_bounds_only: bool = True) -> set[tuple[int, int]]:
    rng = entity.attack_range or 0
    if rng < 1:
        return set()
    xp, yp = _patterns(entity)
    px, py = entity.position.x, entity.position.y
    out: set[tuple[int, int]] = set()
    for dx, dy in zip(xp, yp):
        for j in range(1, rng + 1):
            tx, ty = px + dx * j, py + dy * j
            if in_bounds_only and not in_bounds(tx, ty):
                break
            out.add((tx, ty))
    return out


def entity_threat_tiles_with_move(entity, *, in_bounds_only: bool = True) -> set[tuple[int, int]]:
    rng = entity.attack_range or 0
    if rng < 1:
        return set()
    xp, yp = _patterns(entity)
    move = max(0, entity.max_move_distance or 0)
    px, py = entity.position.x, entity.position.y
    out: set[tuple[int, int]] = set()
    for adx in range(-move, move + 1):
        rem = move - abs(adx)
        for ady in range(-rem, rem + 1):
            ax, ay = px + adx, py + ady
            for dx, dy in zip(xp, yp):
                for j in range(1, rng + 1):
                    tx, ty = ax + dx * j, ay + dy * j
                    if in_bounds_only and not in_bounds(tx, ty):
                        break
                    out.add((tx, ty))
    return out


def enemy_summons(state: GameState, me: Player, enemy: Optional[Player]) -> list[Entity]:
    out: list[Entity] = []
    for _, _, t in iter_cells(state.map):
        e = t.entity
        if e is None or e.summoned_by is None:
            continue
        if e.summoned_by == me.id:
            continue
        if e.health <= 0:
            continue
        out.append(e)
    return out


def threat_attackers(state: GameState, me: Player, enemy: Optional[Player],
                     include_player: bool = True) -> list[Entity]:
    attackers: list = [a for a in enemy_summons(state, me, enemy) if not _is_fatigued(a)]
    if include_player and enemy is not None and not _is_fatigued(enemy):
        attackers.append(enemy)
    return attackers


def threat_map(state: GameState, me: Player, enemy: Optional[Player], *,
               include_player: bool = True, with_move: bool = False) -> dict[tuple[int, int], int]:
    tiles_fn = entity_threat_tiles_with_move if with_move else entity_threat_tiles
    dmg: dict[tuple[int, int], int] = {}
    for a in threat_attackers(state, me, enemy, include_player=include_player):
        ap = a.attack_power or 0
        if ap <= 0:
            continue
        for tile in tiles_fn(a):
            dmg[tile] = dmg.get(tile, 0) + ap
    return dmg


def incoming_at(threat: dict[tuple[int, int], int], xy: tuple[int, int]) -> int:
    return threat.get(xy, 0)


# ===== inlined from bots/engine/engine.py =====
import logging
import sys
import time
from typing import Optional

import requests

import os
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)




log = logging.getLogger("bot")


def legal(action: Action, ctx: RuleContext) -> bool:
    state, me, enemy = ctx.state, ctx.me, ctx.enemy

    if action.kind == "move":
        if action.target_x is None or action.target_y is None:
            return False
        reach = reachable_positions(state, me)
        if me.active_statuses.get(Status.Dizzy, 0) > 0:
            inv = dizzy_request_position(me.position, (action.target_x, action.target_y))
            return inv in reach
        return (action.target_x, action.target_y) in reach

    if action.kind == "attack":
        if action.target_id is None:
            return False
        if is_fatigued(me):
            return False
        target_pos = None
        target = state.players.get(str(action.target_id))
        if target is not None:
            target_pos = target.position
        else:
            for nx, ny in orthogonal_neighbors(me.position):
                t = tile_at(state.map, nx, ny)
                if t and t.entity and t.entity.id == action.target_id:
                    target_pos = Position(nx, ny)
                    break
        if target_pos is None or not is_adjacent(me.position, target_pos):
            return False
        return True

    if action.kind == "use_item":
        if action.item_id is None:
            return False
        return any(it.id == action.item_id for it in me.inventory)

    if action.kind == "pickup_item":
        if action.target_x is None or action.target_y is None:
            return False
        if not is_adjacent(me.position, Position(action.target_x, action.target_y)):
            return False
        t = tile_at(state.map, action.target_x, action.target_y)
        return t is not None and t.item is not None

    if action.kind == "pickup_card":
        if action.target_x is None or action.target_y is None:
            return False
        if not is_adjacent(me.position, Position(action.target_x, action.target_y)):
            return False
        t = tile_at(state.map, action.target_x, action.target_y)
        return t is not None and t.monster_card is not None

    if action.kind == "summon":
        if action.card_id is None or action.target_x is None or action.target_y is None:
            return False
        card = next((c for c in me.cards if c.id == action.card_id and not c.on_cooldown and (c.uses or 0) > 0), None)
        if card is None:
            return False
        return can_summon_on(state, me.position, (action.target_x, action.target_y))

    return False


class ActionExecutor:

    def __init__(self, server_url: str, game_id: str, timeout: float = 5.0):
        self.base = server_url.rstrip("/")
        self.game_id = game_id
        self.timeout = timeout

    _HEADERS = {"No-UI": "1"}

    def _put(self, path: str, body: Optional[dict] = None) -> requests.Response:
        return requests.put(f"{self.base}{path}", json=body, headers=self._HEADERS, timeout=self.timeout)

    def _get(self, path: str) -> requests.Response:
        return requests.get(f"{self.base}{path}", headers=self._HEADERS, timeout=self.timeout)

    def valid_moves(self, player_id: int) -> Optional[list]:
        try:
            r = self._get(f"/player/{player_id}/valid-moves/gameId/{self.game_id}")
            if 200 <= r.status_code < 300:
                return r.json()
        except requests.RequestException:
            pass
        return None

    def execute(self, action: Action, me: Player, state: Optional[GameState] = None) -> requests.Response:
        if action.kind == "move":
            tx, ty = action.target_x, action.target_y
            if me.active_statuses.get(Status.Dizzy, 0) > 0:
                tx, ty = dizzy_request_position(me.position, (tx, ty))
            return self._put(
                f"/player/move/gameId/{self.game_id}",
                {"playerId": me.id, "newPosition": {"X": tx, "Y": ty}},
            )
        if action.kind == "attack":
            return self._put(
                f"/player/{me.id}/attack/{action.target_id}/gameId/{self.game_id}"
            )
        if action.kind == "use_item":
            return self._put(
                f"/player/{me.id}/use-item/{action.item_id}/gameId/{self.game_id}"
            )
        if action.kind == "pickup_item":
            body = _field_info_body(state, action.target_x, action.target_y)
            return self._put(f"/player/pickup/{me.id}/gameId/{self.game_id}", body)
        if action.kind == "pickup_card":
            body = _field_info_body(state, action.target_x, action.target_y)
            return self._put(f"/map/pickup/{me.id}/gameId/{self.game_id}", body)
        if action.kind == "summon":
            return self._put(
                f"/map/{me.id}/summon/{action.card_id}/gameId/{self.game_id}",
                {"X": action.target_x, "Y": action.target_y},
            )
        raise ValueError(f"Unknown action kind: {action.kind}")


def _field_info_body(state: Optional[GameState], x: int, y: int) -> dict:
    if state is None:
        return {"Position": {"X": x, "Y": y}}
    cell = state.map.get_cell(x, y)
    if cell is None:
        return {"Position": {"X": x, "Y": y}}
    body = {
        "Position": {"X": x, "Y": y},
        "Entity": None,
        "FieldType": int(cell.field_type),
        "Owner": None,
        "Item": None,
        "MonsterCard": None,
        "Obstacle": None,
    }
    if cell.item is not None:
        body["Item"] = {
            "Id": cell.item.id,
            "Name": cell.item.name,
            "Uses": cell.item.uses,
            "Effect": cell.item.effect,
            "Range": cell.item.range,
            "Power": cell.item.power,
            "Duration": cell.item.duration,
            "ItemType": int(cell.item.item_type),
        }
    if cell.monster_card is not None:
        mc = cell.monster_card
        m = mc.monster
        body["MonsterCard"] = {
            "Id": mc.id,
            "Name": mc.name,
            "Uses": mc.uses,
            "Effect": mc.effect,
            "Power": mc.power,
            "OnCooldown": mc.on_cooldown,
            "Cooldown": mc.cooldown,
            "CooldownCounter": mc.cooldown_counter,
            "Monster": {
                "Id": m.id,
                "Name": m.name,
                "Health": m.health,
                "MaxHealth": m.max_health,
                "AttackPower": m.attack_power,
                "AttackRange": m.attack_range,
                "MaxMoveDistance": m.max_move_distance,
                "Position": {"X": m.position.x, "Y": m.position.y} if m.position else None,
                "SummonedByPlayerId": m.summoned_by,
                "xPattern": m.x_pattern,
                "yPattern": m.y_pattern,
            } if m is not None else None,
        }
    return body


def idle_pass_action(ctx: RuleContext) -> Optional[Action]:
    state, me = ctx.state, ctx.me

    cards_full = count_cards(me) >= 3
    freeze_full = count_freeze(me) >= 3

    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(state.map, nx, ny)
        if t is None:
            continue
        if t.item is not None:
            item_name = (t.item.name or "").strip().lower()
            if item_name == ITEM_FREEZE_NAME.lower() and freeze_full:
                continue
            return Action(kind="pickup_item", target_x=nx, target_y=ny,
                          rule_name="idle_pickup_item")
        if t.monster_card is not None and not cards_full:
            return Action(kind="pickup_card", target_x=nx, target_y=ny,
                          rule_name="idle_pickup_card")

    reach = filter_safe(reachable_positions(state, me), ctx.turn)
    if reach:
        x, y = min(reach, key=lambda xy: abs(xy[0] - me.position.x) + abs(xy[1] - me.position.y))
        return Action(kind="move", target_x=x, target_y=y, rule_name="idle_move")

    if ctx.enemy is not None and not is_fatigued(me):
        return Action(kind="attack", target_id=ctx.enemy.id, rule_name="idle_attack_noop")

    return None


class Strategy:
    name: str = "Strategy"
    rules: list[Rule] = []

    def pick(self, ctx: RuleContext, rejected: Optional[set] = None, bot_logger: logging.Logger = None) -> Optional[Action]:
        rejection_reasons = []
        for rule in self.rules:
            try:
                action = rule(ctx)
            except Exception as e:
                bot_logger.info("rule %s raised %s — skipping", getattr(rule, "__name__", "?"), e)
                log.warning("rule %s raised %s — skipping", getattr(rule, "__name__", "?"), e)
                continue
            if isinstance(action, str):
                rejection_reasons.append(f"{getattr(rule, '__name__', '?')}: {action}")
                continue
            if action is None:
                bot_logger.info("rule %s returned None (no action) — skipping", getattr(rule, "__name__", "?"))
                continue
            if not action.rule_name:
                action.rule_name = getattr(rule, "__name__", "rule")
            if rejected and _action_key(action) in rejected:
                bot_logger.info("rule %s produced previously-rejected action %s — skipping", action.rule_name, action)
                log.debug("rule %s produced previously-rejected action — skipping", action.rule_name)
                continue
            if legal(action, ctx):
                if rejection_reasons and bot_logger:
                    bot_logger.info(_fmt_rejections(rejection_reasons))
                return action
            log.debug("rule %s produced illegal action %s — skipping", action.rule_name, action)
        if rejection_reasons and bot_logger:
            bot_logger.info(_fmt_rejections(rejection_reasons))
        idle = idle_pass_action(ctx)
        if idle is not None and legal(idle, ctx):
            return idle
        return None


def find_me(state: GameState, bot_name: str) -> Optional[Player]:
    for p in state.players.values():
        if p.name == bot_name:
            return p
    return None


def find_enemy(state: GameState, me: Player) -> Optional[Player]:
    for p in state.players.values():
        if p.id != me.id and p.summoned_by is None:
            return p
    return None


def is_my_turn(state: GameState, me: Player) -> bool:
    if me.first:
        return state.state_str == "Player1Turn"
    return state.state_str == "Player2Turn"


def run_bot(strategy: Strategy, server_url: str, game_id: str, bot_name: str,
            poll_interval: float = 0.5, max_idle_polls: int = 600) -> None:
    bot_log = logging.getLogger(f"bot.{bot_name}")
    if not bot_log.handlers:
        formatter = logging.Formatter(
            f"%(asctime)s [{bot_name}/{strategy.name}] %(message)s",
            datefmt="%H:%M:%S",
        )
        
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(formatter)
        bot_log.addHandler(console_handler)
        
        safe_name = "".join(c for c in bot_name if c.isalnum() or c in ("_", "-")).rstrip()
        file_handler = logging.FileHandler(f"bot_actions_{safe_name}.log", mode="w", encoding="utf-8")
        file_handler.setFormatter(formatter)
        bot_log.addHandler(file_handler)
        
        bot_log.setLevel(logging.INFO)
        bot_log.propagate = False
        
    exec_ = ActionExecutor(server_url, game_id)
    base = server_url.rstrip("/")

    me: Optional[Player] = None
    state: Optional[GameState] = None
    waited = 0
    while me is None and waited < max_idle_polls:
        try:
            r = requests.get(f"{base}/game/state/{game_id}", headers={"No-UI": "1"}, timeout=5)
            if r.status_code == 200:
                state = parse_game_state(r.json())
                me = find_me(state, bot_name)
        except requests.RequestException as e:
            pass
        if me is None:
            time.sleep(poll_interval)
            veived_this_turn = waited + 1
    if me is None:
        bot_log.error("could not find player named %r in game %s", bot_name, game_id)
        return

    bot_log.info("connected as player %s (first=%s)", me.id, me.first)
    last_turn_acted = -1
    rejected_this_turn: set[tuple] = set()
    card_cooldown_block: dict[int, int] = {}

    while True:
        try:
            r = requests.get(f"{base}/game/state/{game_id}", headers={"No-UI": "1"}, timeout=5)
            if r.status_code != 200:
                time.sleep(poll_interval)
                continue
            state = parse_game_state(r.json())
        except requests.RequestException as e:
            time.sleep(poll_interval)
            continue

        if state.state_str == "Ending":
            bot_log.info("game ended at turn %s", state.current_turn)
            return

        me = find_me(state, bot_name)
        if me is None:
            bot_log.warning("lost player record; retrying")
            time.sleep(poll_interval)
            continue

        if not is_my_turn(state, me):
            time.sleep(poll_interval)
            continue

        if state.current_turn == last_turn_acted and state.state_str == ("Player1Turn" if me.first else "Player2Turn"):
            time.sleep(poll_interval)
            continue

        if state.current_turn != last_turn_acted:
            rejected_this_turn.clear()
        for cid, unblock_turn in list(card_cooldown_block.items()):
            if state.current_turn < unblock_turn:
                rejected_this_turn.add(("summon", cid))
            else:
                del card_cooldown_block[cid]

        enemy = find_enemy(state, me)
        ctx = RuleContext(state=state, me=me, enemy=enemy, turn=state.current_turn)

        action = strategy.pick(ctx, rejected=rejected_this_turn, bot_logger=bot_log)
        if action is None:
            bot_log.warning("turn %s: no legal action found — yielding turn to server timeout", state.current_turn)
            time.sleep(poll_interval)
            continue
        pos = f"({me.position.x},{me.position.y})"
        hp  = f"hp={me.health}"
        en_str = (f"  vs  en@({enemy.position.x},{enemy.position.y}) hp={enemy.health}"
                  if enemy else "  no enemy")
        bot_log.info("T%02d | me@%s %s%s | %s  [%s]",
                     state.current_turn, pos, hp, en_str, _describe(action), action.rule_name)
        try:
            resp = exec_.execute(action, me, state)
            if action.kind in ("pickup_card", "pickup_item"):
                bot_log.debug("pickup(%s,%s) http=%s", action.target_x, action.target_y, resp.status_code)
            if 200 <= resp.status_code < 300:
                last_turn_acted = state.current_turn
            elif resp.status_code == 409:
                bot_log.error("turn locked out (409) — stopping")
                return
            elif resp.status_code == 400:
                err = resp.text or ""
                if _is_server_crash(err):
                    bot_log.warning("server crash post-action (%s) — action was processed, continuing", action.kind)
                    last_turn_acted = state.current_turn
                else:
                    bot_log.warning("action rejected (400): %s", err[:200])
                    rejected_this_turn.add(_action_key(action))
                    if action.kind == "summon" and action.card_id is not None:
                        card = next((c for c in me.cards if c.id == action.card_id), None)
                        cooldown = card.cooldown if card else 7
                        unblock_at = state.current_turn + cooldown + 1
                        card_cooldown_block[action.card_id] = max(
                            card_cooldown_block.get(action.card_id, 0), unblock_at
                        )
                        bot_log.warning("card %s blocked until turn %s", action.card_id, unblock_at)
            else:
                bot_log.warning("unexpected status (%s): %s", resp.status_code, resp.text)
        except requests.RequestException as e:
            bot_log.warning("PUT failed: %s", e)

        time.sleep(poll_interval)


def _fmt_rejections(reasons: list[str]) -> str:
    lines = ["  skipped:"]
    for r in reasons:
        name, sep, msg = r.partition(": ")
        parts = name.split("_", 2)
        short = parts[2] if len(parts) == 3 and parts[1].isdigit() else name
        lines.append(f"    x {short}: {msg}" if sep else f"    x {r}")
    return "\n".join(lines)


def _is_server_crash(body: str) -> bool:
    return any(marker in body for marker in ("System.", "at Server.", "Collection was modified"))


def _action_key(a: Action) -> tuple:
    if a.kind == "summon":
        return ("summon", a.card_id)
    return (a.kind, a.target_id, a.card_id, a.item_id, a.target_x, a.target_y)


def _describe(a: Action) -> str:
    if a.kind == "move":
        return f"move({a.target_x},{a.target_y})"
    if a.kind == "attack":
        return f"attack(id={a.target_id})"
    if a.kind == "use_item":
        return f"use_item(id={a.item_id})"
    if a.kind == "pickup_item":
        return f"pickup_item({a.target_x},{a.target_y})"
    if a.kind == "pickup_card":
        return f"pickup_card({a.target_x},{a.target_y})"
    if a.kind == "summon":
        return f"summon(card={a.card_id} at {a.target_x},{a.target_y})"
    return a.kind


# ===== inlined from bots/strategies/base_rules.py =====
from typing import Optional, Union



def r1_1_lethal_kill(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None or is_fatigued(me):
        return "No enemy or player is fatigued"
    if attackable_adjacent_enemy_tile(me, enemy) is None:
        return "Enemy not in valid adjacent attack position"
    if me.attack_power < enemy.health:
        return "Attack power insufficient for lethal"
    return Action(kind="attack", target_id=enemy.id, rule_name="R1.1_lethal_kill")


def r1_2_shrink_escape(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if not in_shrink_danger(me.position, ctx.turn):
        return "Not in shrink danger zone"
    reach = reachable_positions(ctx.state, me)
    safe = filter_safe(reach, ctx.turn)
    if not safe:
        return "No safe reachable positions available"
    def key(xy):
        d_self = abs(xy[0] - me.position.x) + abs(xy[1] - me.position.y)
        d_enemy = (abs(xy[0] - enemy.position.x) + abs(xy[1] - enemy.position.y)
                   if enemy is not None else 0)
        return (d_self, -d_enemy)
    x, y = min(safe, key=key)
    return Action(kind="move", target_x=x, target_y=y, rule_name="R1.2_shrink_escape")


def r1_3_heal_or_die(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None:
        return "No enemy threat detected"
    if me.health > enemy.attack_power + SPIKE_DAMAGE:
        return "Health sufficient to survive next hit"
    heal = find_item_by_name(me, ITEM_HEAL_NAME)
    if heal is not None:
        return Action(kind="use_item", item_id=heal.id, rule_name="R1.3_heal_use")
    tile = adjacent_item_tile(ctx.state, me, item_name=ITEM_HEAL_NAME)
    if tile is not None:
        return Action(kind="pickup_item", target_x=tile[0], target_y=tile[1],
                      rule_name="R1.3_heal_pickup")
    return "No heal items available (using none)"


def r1_4_use_dizzy_scroll(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None:
        return "No enemy detected"
    item = find_item_by_name(me, ITEM_DIZZY_NAME)
    if item is None:
        return "No dizzy scroll in inventory"
    if has_status(enemy, Status.Dizzy) or has_status(enemy, Status.Frozen):
        return "Enemy already dizzy or frozen"
    rng = item.range if item.range is not None else 3
    if manhattan(me.position, enemy.position) > rng:
        return "Enemy out of dizzy scroll range"
    return Action(kind="use_item", item_id=item.id, rule_name="R1.4_use_dizzy")


def r_attack_enemy_summon(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None or is_fatigued(me):
        return "No enemy or player is fatigued"
    summon_id = attackable_adjacent_summon(ctx.state, me, enemy)
    if summon_id is None:
        return "No attackable adjacent enemy summon found"
    return Action(kind="attack", target_id=summon_id, rule_name="R_attack_enemy_summon")


SHARED_TOP: list = [r1_1_lethal_kill, r1_2_shrink_escape, r1_3_heal_or_die, r1_4_use_dizzy_scroll]
SHARED_BOTTOM: list = [r_attack_enemy_summon]


# ===== inlined from bots/strategies/hunter/rules_hunter.py =====
import math
from typing import Callable, Optional, Union



CARD_VALUE_ICE_CUBE = 25.0
CARD_VALUE_MAGE     = 70.0
CARD_VALUE_WARRIOR  = 60.0

ITEM_VALUE_HEAL     = 20.0
ITEM_VALUE_FREEZE   = 12.0

MY_DIST_PENALTY  = 0.3
ENEMY_PROX_BONUS = 0.2

GRAVE_DANGER_BUFFER = 21
COMMIT_TO_GOAL_BUFFER = 15

LATE_GAME_TURN           = 100
LATE_GAME_HEAL_THRESHOLD = 100

MAX_FREEZE_STACK = 3
MAX_HEAL_STACK   = 3
MAX_CARD_HAND    = 3

MAP_CENTER_X  = 15.5
MAP_CENTER_Y  = 7.5
_MAP_MAX_DIST = MAP_CENTER_X + MAP_CENTER_Y
CENTER_BONUS  = 0.15

ITEM_REFRESH_TURNS = 20
REFRESH_VALUE      = 100.0
REFRESH_LOOKAHEAD  = 6


_bfs_cache: dict = {}
_bfs_cache_now: int = -1


def _bfs_adj(
    state,
    start: tuple[int, int],
    gx: int,
    gy: int,
    turn_filter: Optional[int],
    now: int,
    health: int
) -> Optional[list[tuple[int, int]]]:
    def is_adj(pos: tuple, _gx: int = gx, _gy: int = gy) -> bool:
        return abs(pos[0] - _gx) + abs(pos[1] - _gy) == 1
    if turn_filter is not None:
        result = bfs_path(state, start, is_adj, turn=turn_filter, health=health)
    else:
        result = bfs_path(state, start, is_adj, health=health)

    return result if result else None


def _card_tile_base_value(monster_card) -> float:
    if _is_ice_cube_card(monster_card):
        return CARD_VALUE_ICE_CUBE
    if (monster_card.power or 0) >= 35:
        return CARD_VALUE_MAGE
    return CARD_VALUE_WARRIOR


def _item_tile_base_value(item) -> float:
    name = (item.name or "").strip().lower()
    if name == ITEM_HEAL_NAME.strip().lower():
        return ITEM_VALUE_HEAL
    if name == ITEM_FREEZE_NAME.strip().lower():
        return ITEM_VALUE_FREEZE
    return 0.0


def _turns_for_path(path: list[tuple[int, int]]) -> int:
    return len(path) - 1


def _find_best_goal(
    ctx: RuleContext,
) -> tuple[Optional[tuple[int, int]], Optional[list[tuple[int, int]]]]:
    me, enemy = ctx.me, ctx.enemy
    my_pos = (me.position.x, me.position.y)
    enemy_pos = (enemy.position.x, enemy.position.y) if enemy else None

    best_score = -1.0
    best_goal: Optional[tuple[int, int]] = None
    best_path: Optional[list[tuple[int, int]]] = None

    fb_score = -1.0
    fb_goal: Optional[tuple[int, int]] = None
    fb_path: Optional[list[tuple[int, int]]] = None

    for gx, gy, t in iter_cells(ctx.state.map):
        if t.monster_card is None and t.item is None:
            continue
        if abs(gx - me.position.x) + abs(gy - me.position.y) <= 1:
            continue
        if t.monster_card is not None:
            uses = t.monster_card.uses or 1
            base_value = _card_tile_base_value(t.monster_card) * (uses + 1) / 2
            if count_cards(me) >= MAX_CARD_HAND:
                continue
        else:
            base_value = _item_tile_base_value(t.item)
            if base_value == 0.0:
                continue
            name_lc = (t.item.name or "").strip().lower()
            if name_lc == ITEM_FREEZE_NAME.strip().lower():
                if count_freeze(me) >= MAX_FREEZE_STACK:
                    continue
            elif name_lc == ITEM_HEAL_NAME.strip().lower():
                if count_heal(me) >= MAX_HEAL_STACK:
                    continue

        my_path = _bfs_adj(ctx.state, my_pos, gx, gy, turn_filter=ctx.turn, now=ctx.turn, health=ctx.me.health)
        if not my_path:
            continue
        my_turns = _turns_for_path(my_path)

        if enemy is not None and find_item_by_name(me, ITEM_HEAL_NAME) is None:
            if _path_damage_estimate(ctx, my_path) >= me.health:
                continue

        center_dist = abs(gx - MAP_CENTER_X) + abs(gy - MAP_CENTER_Y)
        center_factor = 1.0 + CENTER_BONUS * (1.0 - center_dist / _MAP_MAX_DIST)

        fb_raw = base_value * center_factor / (1.0 + my_turns * MY_DIST_PENALTY)
        if fb_raw > fb_score:
            fb_score = fb_raw
            fb_goal = (gx, gy)
            fb_path = my_path

        enemy_turns: Optional[int] = None
        if enemy_pos is not None:
            enemy_path = _bfs_adj(ctx.state, enemy_pos, gx, gy, turn_filter=None, now=ctx.turn, health=ctx.me.health)
            if enemy_path is not None:
                enemy_turns = _turns_for_path(enemy_path)
                if my_turns > enemy_turns:
                    continue

        prox = (1.0 + enemy_turns * ENEMY_PROX_BONUS) if enemy_turns is not None else 1.0
        score = base_value * center_factor / (1.0 + my_turns * MY_DIST_PENALTY) * prox

        if score > best_score:
            best_score = score
            best_goal = (gx, gy)
            best_path = my_path

    turns_until_refresh = ITEM_REFRESH_TURNS - (ctx.turn % ITEM_REFRESH_TURNS)
    if turns_until_refresh <= REFRESH_LOOKAHEAD:
        for cgx, cgy in [(15, 7), (16, 7), (15, 8), (16, 8)]:
            c_path = _bfs_adj(ctx.state, my_pos, cgx, cgy,
                              turn_filter=ctx.turn, now=ctx.turn, health=me.health)
            if not c_path:
                continue
            effective_turns = _turns_for_path(c_path) + turns_until_refresh
            r_score = REFRESH_VALUE / (1.0 + effective_turns * MY_DIST_PENALTY)
            if r_score > best_score:
                best_score = r_score
                best_goal = (cgx, cgy)
                best_path = c_path
            if r_score > fb_score:
                fb_score = r_score
                fb_goal = (cgx, cgy)
                fb_path = c_path
            break

    if best_goal is not None:
        return best_goal, best_path
    return fb_goal, fb_path


def _path_damage_estimate(ctx: RuleContext, path: list[tuple[int, int]]) -> int:
    if ctx.enemy is None:
        return 0
    t_map = threat_map(ctx.state, ctx.me, ctx.enemy, include_player=True)
    return sum(t_map.get(pos, 0) for pos in path[1:])


def _off_path_targets(ctx: RuleContext, all_targets: list) -> list:
    _, plan_path = _find_best_goal(ctx)
    if not plan_path:
        return all_targets
    path_set = set(plan_path)
    off_path = [xy for xy in all_targets if xy not in path_set]
    return off_path if off_path else all_targets


def _enemy_goal_path(ctx: RuleContext) -> Optional[list[tuple[int, int]]]:
    enemy = ctx.enemy
    if enemy is None:
        return None
    enemy_pos = (enemy.position.x, enemy.position.y)

    best_score = -1.0
    best_path: Optional[list[tuple[int, int]]] = None

    for gx, gy, t in iter_cells(ctx.state.map):
        if t.monster_card is None and t.item is None:
            continue
        if t.monster_card is not None:
            base_value = _card_tile_base_value(t.monster_card)
        else:
            base_value = _item_tile_base_value(t.item)
            if base_value == 0.0:
                continue

        enemy_path = _bfs_adj(ctx.state, enemy_pos, gx, gy, turn_filter=None, now=ctx.turn, health=ctx.me.health)
        if enemy_path is None:
            continue
        center_dist = abs(gx - MAP_CENTER_X) + abs(gy - MAP_CENTER_Y)
        center_factor = 1.0 + CENTER_BONUS * (1.0 - center_dist / _MAP_MAX_DIST)
        score = base_value * center_factor / (1.0 + _turns_for_path(enemy_path) * MY_DIST_PENALTY)
        if score > best_score:
            best_score = score
            best_path = enemy_path

    return best_path


def w1_1_cornered_heal(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None:
        return "No enemy"

    my_xy = (me.position.x, me.position.y)
    t_map = threat_map(ctx.state, me, enemy, include_player=True)
    incoming = t_map.get(my_xy, 0)

    if me.health > incoming + SPIKE_DAMAGE + GRAVE_DANGER_BUFFER:
        return "Not in grave danger"
    if incoming <= 0:
        return "No incoming damage on current tile"

    heal = find_item_by_name(me, ITEM_HEAL_NAME)
    if heal is None:
        return "No heal in inventory"

    reach = filter_safe(reachable_positions(ctx.state, me), ctx.turn)
    retreat = step_away_from(reach, me, (enemy.position.x, enemy.position.y), ctx.turn)
    
    if (incoming <= 25 or retreat is None) and ctx.me.health < GRAVE_DANGER_BUFFER:
        return Action(kind="use_item", item_id=heal.id, rule_name="W1.1_cornered_heal")

    return "Retreat possible, prefer fleeing to healing"

def w1_2_freeze_into_shrink(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None or not has_freeze(me):
        return "No enemy or no freeze items"
    turn = ctx.turn
    if turn >= 45:
        return "No more shrinks remaining"
    next_shrink = 15 if turn < 15 else 30 if turn < 30 else 45
    if not in_shrink_danger(enemy.position, turn):
        return "Enemy not in shrink danger zone"
    turns_until = next_shrink - turn
    if count_freeze(me) * 2 < turns_until:
        return "Not enough freezes to cover until shrink fires"
    current_frozen = enemy.active_statuses.get(Status.Frozen, 0)
    if current_frozen >= turns_until:
        return "Enemy already frozen long enough to die in shrink"
    item = find_item_by_name(me, ITEM_FREEZE_NAME)
    if item is None:
        return "Freeze item not found"
    return Action(kind="use_item", item_id=item.id, rule_name="W1.2_freeze_into_shrink")


def w1_3_late_game_heal(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    if ctx.turn <= LATE_GAME_TURN - count_heal(me):
        return "Not late game yet"
    if me.health >= LATE_GAME_HEAL_THRESHOLD:
        return "HP already high enough"
    heal = find_item_by_name(me, ITEM_HEAL_NAME)
    if heal is None:
        return "No heal in inventory"
    return Action(kind="use_item", item_id=heal.id, rule_name="W1.3_late_game_heal")


def w1_4_attack_enemy_player(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None:
        return "No enemy"
    if is_fatigued(me):
        return "We are fatigued"
    if not is_adjacent(me.position, enemy.position):
        return "Enemy not adjacent"

    my_dmg = me.attack_power
    for nx, ny in orthogonal_neighbors(enemy.position):
        t = tile_at(ctx.state.map, nx, ny)
        if t and t.entity and t.entity.summoned_by == me.id and not is_fatigued(t.entity):
            my_dmg += t.entity.attack_power

    t_map = threat_map(ctx.state, me, enemy, include_player=True)
    their_dmg = t_map.get((me.position.x, me.position.y), 0)

    if my_dmg <= their_dmg:
        return f"Enemy out-damages us ({their_dmg} vs {my_dmg})"
    if me.health <= their_dmg:
        return "Cannot survive incoming damage"

    return Action(kind="attack", target_id=enemy.id, rule_name="W1.4_attack_enemy_player")


def _blocking_summon_target(ctx: RuleContext, all_targets: list) -> Optional[tuple[int, int]]:
    ep = _enemy_goal_path(ctx)
    if not ep:
        return None
    path_index = {(x, y): i for i, (x, y) in enumerate(ep)}
    blocking = [(path_index[xy], xy) for xy in all_targets if xy in path_index]
    if not blocking:
        return None
    _, best = max(blocking)
    return best


def _pick_summon_target(ctx: RuleContext, all_targets: list) -> tuple[int, int]:
    block = _blocking_summon_target(ctx, all_targets)
    if block is not None:
        return block
    targets = _off_path_targets(ctx, all_targets)
    enemy = ctx.enemy
    if enemy is not None:
        ex, ey = enemy.position.x, enemy.position.y
        return min(targets, key=lambda xy: abs(xy[0] - ex) + abs(xy[1] - ey))
    return targets[0]


def w2_1_freeze_into_summon_pattern(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None or not has_freeze(me):
        return "No enemy or no freeze items"

    enemy_xy = (enemy.position.x, enemy.position.y)
    allied = find_allied_summons(ctx.state, me)
    if not any(enemy_xy in entity_threat_tiles_with_move(s) for s in allied):
        return "Enemy not in any allied summon's strike pattern"

    if enemy.active_statuses.get(Status.Frozen, 0) >= 2:
        return "Enemy already frozen 2+ turns"
    item = find_item_by_name(me, ITEM_FREEZE_NAME)
    if item is None:
        return "Freeze item not found"
    return Action(kind="use_item", item_id=item.id, rule_name="W2.1_freeze_into_summon_pattern")


def w2_2_summon_warrior(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    cards = available_warrior_cards(me)
    if not cards:
        return "No warrior cards available"
    all_targets = summon_targets(ctx.state, me)
    if not all_targets:
        return "No summon targets"
    tx, ty = _pick_summon_target(ctx, all_targets)
    return Action(kind="summon", card_id=pick_card_max_uses(cards).id, target_x=tx, target_y=ty,
                  rule_name="W2.2_summon_warrior")


def w2_3_summon_mage(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    cards = available_mage_cards(me)
    if not cards:
        return "No mage cards available"
    all_targets = summon_targets(ctx.state, me)
    if not all_targets:
        return "No summon targets"
    tx, ty = _pick_summon_target(ctx, all_targets)
    return Action(kind="summon", card_id=pick_card_max_uses(cards).id, target_x=tx, target_y=ty,
                  rule_name="W2.3_summon_mage")


def w2_4_summon_cube(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    cards = available_cube_cards(me)
    if not cards:
        return "No ice cube cards available"
    all_targets = summon_targets(ctx.state, me)
    if not all_targets:
        return "No summon targets"
    tx, ty = _pick_summon_target(ctx, all_targets)
    return Action(kind="summon", card_id=pick_card_max_uses(cards).id, target_x=tx, target_y=ty,
                  rule_name="W2.4_summon_cube")


def w3_1_kill_adjacent_mob(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    if enemy is None:
        return "No enemy"
    if is_fatigued(me):
        return "We are fatigued"
    if is_adjacent(me.position, enemy.position):
        return "Enemy player also adjacent — skip mob"
    mobs = [
        t.entity
        for nx, ny in orthogonal_neighbors(me.position)
        if (t := tile_at(ctx.state.map, nx, ny)) and t.entity
        and t.entity.summoned_by == enemy.id
    ]
    if not mobs:
        return "No adjacent enemy mobs"
    if len(mobs) > 1:
        return "Multiple mobs adjacent"
    mob = mobs[0]
    if not me.attack_power:
        return "Zero attack power"
    turns_to_kill = math.ceil(mob.health / me.attack_power)
    if turns_to_kill > 2:
        return "Cannot kill mob within 2 turns"
    total_incoming = turns_to_kill * mob.attack_power
    if me.health <= total_incoming + COMMIT_TO_GOAL_BUFFER:
        return "Not enough HP to survive mob fight"
    return Action(kind="attack", target_id=mob.id, rule_name="W3.1_kill_adjacent_mob")


def w4_1_pickup_warrior_card(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    if len(me.cards) >= MAX_CARD_HAND:
        return "Hand full"
    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(ctx.state.map, nx, ny)
        if t and t.monster_card and _is_warrior_card(t.monster_card):
            return Action(kind="pickup_card", target_x=nx, target_y=ny,
                          rule_name="W4.1_pickup_warrior_card")
    return "No adjacent warrior card"


def w4_2_pickup_mage_card(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    if len(me.cards) >= MAX_CARD_HAND:
        return "Hand full"
    for nx, ny in orthogonal_neighbors(me.position):
        t = tile_at(ctx.state.map, nx, ny)
        if t and t.monster_card and _is_mage_card(t.monster_card):
            return Action(kind="pickup_card", target_x=nx, target_y=ny,
                          rule_name="W4.2_pickup_mage_card")
    return "No adjacent mage card"


def w4_3_pickup_cube_card(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    if count_cards(me) >= MAX_CARD_HAND:
        return "Hand full"
    tile = adjacent_card_tile(ctx.state, me, ice_cube_only=True)
    if tile is None:
        return "No adjacent cube card"
    return Action(kind="pickup_card", target_x=tile[0], target_y=tile[1],
                  rule_name="W4.3_pickup_cube_card")


def w4_4_pickup_freeze(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    if count_freeze(me) >= MAX_FREEZE_STACK:
        return "Freeze stack full"
    tile = adjacent_item_tile(ctx.state, me, item_name=ITEM_FREEZE_NAME)
    if tile is None:
        return "No adjacent freeze scroll"
    return Action(kind="pickup_item", target_x=tile[0], target_y=tile[1],
                  rule_name="W4.4_pickup_freeze")


def w4_5_pickup_heal(ctx: RuleContext) -> Union[Action, str]:
    me = ctx.me
    tile = adjacent_item_tile(ctx.state, me, item_name=ITEM_HEAL_NAME)
    if tile is None:
        return "No adjacent heal item"
    return Action(kind="pickup_item", target_x=tile[0], target_y=tile[1],
                  rule_name="W4.5_pickup_heal")

def w4_6_go_center_fast(ctx: RuleContext) -> Union[Action, str]:
    pos = ctx.me.position
    m = ctx.state.map
    if not (is_in_bridge_wall_zone(pos) and ctx.turn > 35):
        return "No need to rush center"
    index = m.pair_to_index(pos.x, pos.y)
    safe = filter_safe(
        {m.index_to_pair(n) for n in m.graph.neighbors(index)}, ctx.turn
    )
    best_dist = 1000.0
    best_move: Optional[tuple[int, int]] = None
    for nx, ny in safe:
        dist = abs(nx - MAP_CENTER_X) + abs(ny - MAP_CENTER_Y)
        if dist < best_dist:
            best_dist = dist
            best_move = (nx, ny)
    if best_move is None:
        return "No safe step toward center"
    return Action(kind="move", target_x=best_move[0], target_y=best_move[1],
                  rule_name="W4.6_go_center_fast")


def _threat_aware_step(
    ctx: RuleContext,
    is_goal: Callable[[tuple[int, int]], bool],
    threat: dict[tuple[int, int], int],
) -> Optional[tuple[int, int]]:
    reach = filter_safe(reachable_positions(ctx.state, ctx.me), ctx.turn)
    if not reach:
        return None
    scored = []
    for xy in reach:
        path = bfs_path(ctx.state, xy, is_goal, turn=ctx.turn, health=ctx.me.health)
        d = len(path) - 1 if path else None
        if d is None:
            continue
        thr = threat.get(xy, 0)
        scored.append((thr > 0, thr, d, xy))
    if not scored:
        return None
    scored.sort(key=lambda s: (s[0], s[1], s[2]))
    return scored[0][3]


def w5_1_navigate_best_goal(ctx: RuleContext) -> Union[Action, str]:
    me, enemy = ctx.me, ctx.enemy
    threat = threat_map(ctx.state, me, enemy, include_player=True)

    best_goal, best_path = _find_best_goal(ctx)

    if not best_path:
        heal = find_item_by_name(me, ITEM_HEAL_NAME)
        if heal is not None:
            return Action(kind="use_item", item_id=heal.id,
                            rule_name="W5.1_heal_before_path")

    if best_goal is not None and best_path:
        bgx, bgy = best_goal

        def is_adj_goal(pos: tuple, _gx: int = bgx, _gy: int = bgy) -> bool:
            return abs(pos[0] - _gx) + abs(pos[1] - _gy) == 1

        step = _threat_aware_step(ctx, is_adj_goal, threat)
        if step is not None:
            direct_step = best_path[1] if len(best_path) >= 2 else None
            if (direct_step is not None
                    and (threat.get(direct_step, 0) == 0 or me.health > threat.get(direct_step, 0) + COMMIT_TO_GOAL_BUFFER)):
                step = direct_step
                flag = True
            return Action(kind="move", target_x=step[0], target_y=step[1],
                          rule_name="W5.1_navigate_best_goal" + str(best_goal) + str(flag))

    if enemy is None:
        return "No goals and no enemy"
    ex, ey = enemy.position.x, enemy.position.y

    def is_near_enemy(pos: tuple) -> bool:
        return abs(pos[0] - ex) + abs(pos[1] - ey) <= 3

    step = _threat_aware_step(ctx, is_near_enemy, threat)
    if step is None:
        return "No path toward enemy"
    return Action(kind="move", target_x=step[0], target_y=step[1],
                  rule_name="W5.1_press_toward_enemy")

def w6_1_go_center_faster(ctx: RuleContext) -> Union[Action, str]:
    pos = ctx.me.position
    m = ctx.state.map
    index = m.pair_to_index(pos.x, pos.y)
    best_dist = 1000.0
    best_move: Optional[tuple[int, int]] = None
    for nx, ny in m.graph.neighbors(index):
        dist = abs(nx - MAP_CENTER_X) + abs(ny - MAP_CENTER_Y)
        if dist < best_dist:
            best_dist = dist
            best_move = (nx, ny)
    if best_move is None:
        return "No safe step toward center"
    return Action(kind="move", target_x=best_move[0], target_y=best_move[1],
                  rule_name="W4.6_go_center_fast")


HUNTER_RULES: list = [
    w1_1_cornered_heal,
    w1_2_freeze_into_shrink,
    w1_3_late_game_heal,
    w1_4_attack_enemy_player,
    w2_1_freeze_into_summon_pattern,
    w2_2_summon_warrior,
    w2_3_summon_mage,
    w2_4_summon_cube,
    w3_1_kill_adjacent_mob,
    w4_1_pickup_warrior_card,
    w4_2_pickup_mage_card,
    w4_3_pickup_cube_card,
    w4_4_pickup_freeze,
    w4_5_pickup_heal,
    w4_6_go_center_fast,
    w5_1_navigate_best_goal,
    w6_1_go_center_faster,
]



# ── Standalone entry point ────────────────────────────────────────────────

class HunterStrategy(Strategy):
    name = "Hunter"
    rules = [r1_1_lethal_kill, r1_2_shrink_escape] + HUNTER_RULES + SHARED_BOTTOM


def main() -> None:
    if len(sys.argv) < 4:
        print("Usage: python bot_hunter.py <server_url> <game_id> <bot_name>")
        sys.exit(1)
    run_bot(HunterStrategy(), sys.argv[1], sys.argv[2], sys.argv[3])


if __name__ == "__main__":
    main()
